apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: dev

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: dev
subjects:
- kind: ServiceAccount
  name: app-service-account
  namespace: dev 
roleRef:
  kind: Role
  name: pod-reader 
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-azurefile
  namespace: dev
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-rwx
  resources:
    requests:
      storage: 5Gi